apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: printnow-common-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/printnow-dev/printnow.git
    targetRevision: dev
    path: helm/common
    helm:
      valueFiles:
        - values-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: user-service-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/printnow-dev/printnow.git
    targetRevision: dev
    path: helm/services/user-service
    helm:
      valueFiles:
        - values-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: printnow-document-service-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/printnow-dev/printnow.git
    targetRevision: dev
    path: helm/services/printnow-document-service
    helm:
      valueFiles:
        - values-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: printnow-order-service-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/printnow-dev/printnow.git
    targetRevision: dev
    path: helm/services/printnow-order-service
    helm:
      valueFiles:
        - values-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: printnow-vendor-service-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/printnow-dev/printnow.git
    targetRevision: dev
    path: helm/services/printnow-vendor-service
    helm:
      valueFiles:
        - values-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: printnow-frontend-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/printnow-dev/printnow.git
    targetRevision: dev
    path: helm/services/printnow-frontend
    helm:
      valueFiles:
        - values-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
